DELIMITER $$

CREATE PROCEDURE test_proc()
BEGIN

        INSERT INTO control_names (id_control, control_name) VALUES ('1F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('2F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('3F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('4F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('5F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('6F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('7F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('9F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('10F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('11F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('12F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('13L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('14L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('15L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('16L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('17L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('18L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('19L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('21F', 'Posición topes BC Tipo 2');
        INSERT INTO control_names (id_control, control_name) VALUES ('22F', 'Posición topes BC Tipo 2');
        INSERT INTO control_names (id_control, control_name) VALUES ('23F', 'Posición topes BC Tipo 2');
        INSERT INTO control_names (id_control, control_name) VALUES ('24L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('25L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('26L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('27L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('28L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('29F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('30F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('31F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('32F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('33F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('34F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('36F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('37F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('38F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('39L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('40L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('41L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('42L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('43L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('44F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('45F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('46F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('47F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('48F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('49F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('51F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('52F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('53F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('54L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('55L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('56L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('57L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('58L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('59F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('60F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('61F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('62F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('63F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('64F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('66F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('67F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('68F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('69L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('70L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('71L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('72L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('73L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('74F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('75F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('76F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('77F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('78F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('79F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('81F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('82F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('83F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('84L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('85L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('86L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('87L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('88L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('89F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('90F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('91F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('92F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('93F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('94F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('96F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('97F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('98F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('99L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('100L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('101L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('102L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('103L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('104F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('105F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('106F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('107F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('108F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('109F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('111F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('112F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('113F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('114L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('115L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('116L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('117L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('118L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('119F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('120F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('121F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('122F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('123F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('124F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('126F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('127F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('128F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('129L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('130L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('131L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('132L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('133L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('134F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('135F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('136F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('137F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('138F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('139F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('141F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('142F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('143F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('144L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('145L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('146L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('147L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('148L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('149F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('150F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('151F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('152F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('153F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('154F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('156F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('157F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('158F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('159L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('160L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('161L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('162L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('163L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('164F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('165F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('166F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('167F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('168F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('169F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('171F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('172F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('173F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('174L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('175L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('176L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('177L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('178L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('179F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('180F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('181F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('182F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('183F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('184F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('186F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('187F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('188F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('189L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('190L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('191L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('192L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('193L', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('194F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('195F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('196F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('197F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('198F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('199F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('201F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('202F', 'Distancia entre SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('203F', 'Ángulo relativo zapatas');
        INSERT INTO control_names (id_control, control_name) VALUES ('001F', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('210F', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('002F', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('211F', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('003F', 'Ángulo pollera SE');
        INSERT INTO control_names (id_control, control_name) VALUES ('212L', 'Ángulo de zapatas (3x1)');
        INSERT INTO control_names (id_control, control_name) VALUES ('213L', 'Ángulo de zapatas (3x1)');
        INSERT INTO control_names (id_control, control_name) VALUES ('214L', 'Ángulo de zapatas (3x1)');
        INSERT INTO control_names (id_control, control_name) VALUES ('216L', 'Presencia de soldadura TVS');
        INSERT INTO control_names (id_control, control_name) VALUES ('217L', 'Presencia de soldadura TVS');
        INSERT INTO control_names (id_control, control_name) VALUES ('218L', 'Presencia de soldadura TVS');
        INSERT INTO control_names (id_control, control_name) VALUES ('222L', 'Deformación TS');
        INSERT INTO control_names (id_control, control_name) VALUES ('223L', 'Deformación TS');
        INSERT INTO control_names (id_control, control_name) VALUES ('224L', 'Deformación TS');
        INSERT INTO control_names (id_control, control_name) VALUES ('225L', 'Deformación TS');
        INSERT INTO control_names (id_control, control_name) VALUES ('226L', 'Deformación TS');
        INSERT INTO control_names (id_control, control_name) VALUES ('227L', 'Deformación TS');
        INSERT INTO control_names (id_control, control_name) VALUES ('228L', 'Deformación TVI');
        INSERT INTO control_names (id_control, control_name) VALUES ('229L', 'Deformación TVI');
        INSERT INTO control_names (id_control, control_name) VALUES ('230L', 'Deformación TVI');
        INSERT INTO control_names (id_control, control_name) VALUES ('231L', 'Deformación TVI');
        INSERT INTO control_names (id_control, control_name) VALUES ('232L', 'Deformación TVI');
        INSERT INTO control_names (id_control, control_name) VALUES ('233L', 'Deformación TVI');
        INSERT INTO control_names (id_control, control_name) VALUES ('240F', 'Identificación Acople');
        INSERT INTO control_names (id_control, control_name) VALUES ('241F', 'Identificación Acople');
        INSERT INTO control_names (id_control, control_name) VALUES ('242F', 'Identificación Acople');

END $$

DELIMITER ;
