INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('1F', 'Ángulo relativo zapatas', '40°', '+/-30''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('2F', 'Ángulo relativo zapatas', '40°', '+/-30''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('3F', 'Distancia entre SE', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('4F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('5F', 'Ángulo relativo zapatas', '40°', '+/-30''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('6F', 'Distancia entre SE', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('7F', 'Ángulo relativo zapatas', '40°', '+/-30''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('9F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('10F', 'Distancia entre SE', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('11F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('12F', 'Distancia entre SE', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('13L', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('14L', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('15L', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('16L', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('17L', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('18L', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('19L', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('21F', 'Posición topes BC Tipo 2', '80°', '+/-3°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('22F', 'Posición topes BC Tipo 2', '80°', '+/-3°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('23F', 'Posición topes BC Tipo 2', '80°', '+/-3°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('24L', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('25L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('26L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('27L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('28L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('29F', 'Distancia entre SE', '160 mm', '+/-0.5 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('30F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('31F', 'Distancia entre SE', '160 mm', '+/-0.5 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('32F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('33F', 'Distancia entre SE', '160 mm', '+/-0.5 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('34F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('36F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('37F', 'Distancia entre SE', '160 mm', '+/-0.5 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('38F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('39L', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('40L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('41L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('42L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('43L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('44F', 'Distancia entre SE', '340 mm', '+/-0.5 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('45F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('46F', 'Distancia entre SE', '340 mm', '+/-0.5 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('47F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('48F', 'Distancia entre SE', '340 mm', '+/-0.5 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('49F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('51F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('52F', 'Distancia entre SE', '340 mm', '+/-0.5 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('53F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('54L', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('55L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('56L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('57L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('58L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('59F', 'Distancia entre SE', '400 mm', '+/-0.5 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('60F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('61F', 'Distancia entre SE', '400 mm', '+/-0.5 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('62F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('63F', 'Distancia entre SE', '400 mm', '+/-0.5 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('64F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('66F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('67F', 'Distancia entre SE', '400 mm', '+/-0.5 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('68F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('69L', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('70L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('71L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('72L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('73L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('74F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('75F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('76F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('77F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('78F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('79F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('81F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('82F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('83F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('84L', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('85L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('86L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('87L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('88L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('89F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('90F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('91F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('92F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('93F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('94F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('96F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('97F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('98F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('99L', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('100L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('101L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('102L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('103L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('104F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('105F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('106F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('107F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('108F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('109F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('111F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('112F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('113F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('114L', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('115L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('116L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('117L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('118L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('119F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('120F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('121F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('122F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('123F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('124F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('126F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('127F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('128F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('129L', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('130L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('131L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('132L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('133L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('134F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('135F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('136F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('137F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('138F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('139F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('141F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('142F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('143F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('144L', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('145L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('146L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('147L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('148L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('149F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('150F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('151F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('152F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('153F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('154F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('156F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('157F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('158F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('159L', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('160L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('161L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('162L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('163L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('164F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('165F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('166F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('167F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('168F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('169F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('171F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('172F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('173F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('174L', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('175L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('176L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('177L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('178L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('179F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('180F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('181F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('182F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('183F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('184F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('186F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('187F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('188F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('189L', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('190L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('191L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('192L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('193L', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('194F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('195F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('196F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('197F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('198F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('199F', 'Ángulo relativo zapatas', '80°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('201F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('202F', 'Distancia entre SE', '455 mm', '+/-0.8 mm');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('203F', 'Ángulo relativo zapatas', '60°', '+/-20''');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('001F', 'Ángulo pollera SE', '5°', '+/-1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('210F', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('002F', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('211F', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('003F', 'Ángulo pollera SE', '5°', '+2/0°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('212L', 'Ángulo de zapatas (3x1)', '5°', '+0/1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('213L', 'Ángulo de zapatas (3x1)', '5°', '+0/1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('214L', 'Ángulo de zapatas (3x1)', '5°', '+0/1°');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('216L', 'Presencia de soldadura TVS', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('217L', 'Presencia de soldadura TVS', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('218L', 'Presencia de soldadura TVS', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('222L', 'Deformación TS', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('223L', 'Deformación TS', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('224L', 'Deformación TS', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('225L', 'Deformación TS', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('226L', 'Deformación TS', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('227L', 'Deformación TS', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('228L', 'Deformación TVI', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('229L', 'Deformación TVI', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('230L', 'Deformación TVI', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('231L', 'Deformación TVI', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('232L', 'Deformación TVI', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('233L', 'Deformación TVI', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('240F', 'Identificación Acople', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('241F', 'Identificación Acople', 'NA', 'NA');
INSERT INTO control_names (id_control, control_name, valor_esperado, tolerancia) VALUES ('242F', 'Identificación Acople', 'NA', 'NA');