DELETE FROM control_names;

INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('1F', 'Ángulo relativo zapatas', '40°', '+/-30''', '13.0', '24.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('2F', 'Ángulo relativo zapatas', '40°', '+/-30''', '13.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('3F', 'Distancia entre SE', 'NA', 'NA', '13.0', '28.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('4F', 'Ángulo relativo zapatas', '80°', '+/-20''', '13.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('5F', 'Ángulo relativo zapatas', '40°', '+/-30''', '13.0', '32.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('6F', 'Distancia entre SE', 'NA', 'NA', '13.0', '32/33');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('7F', 'Ángulo relativo zapatas', '40°', '+/-30''', '13.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('9F', 'Ángulo relativo zapatas', '60°', '+/-20''', '13.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('10F', 'Distancia entre SE', 'NA', 'NA', '13.0', '20/21');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('11F', 'Ángulo relativo zapatas', '60°', '+/-20''', '13.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('12F', 'Distancia entre SE', 'NA', 'NA', '13.0', '23.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('13L', 'Ángulo pollera SE', '5°', '+/-1°', '13.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('14L', 'Ángulo pollera SE', '5°', '+/-1°', '13.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('15L', 'Ángulo pollera SE', '5°', '+/-1°', '13.0', '32.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('16L', 'Ángulo pollera SE', '5°', '+/-1°', '13.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('17L', 'Ángulo pollera SE', '5°', '+/-1°', '13.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('18L', 'Ángulo pollera SE', '5°', '+/-1°', '13.0', '24.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('19L', 'Ángulo pollera SE', '5°', '+/-1°', '13.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('21F', 'Posición topes BC Tipo 2', '80°', '+/-3°', '13.0', '29.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('22F', 'Posición topes BC Tipo 2', '80°', '+/-3°', '13.0', '35.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('23F', 'Posición topes BC Tipo 2', '80°', '+/-3°', '13.0', '23.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('24L', 'Ángulo pollera SE', '5°', '+/-1°', '12.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('25L', 'Ángulo pollera SE', '5°', '+2/0°', '12.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('26L', 'Ángulo pollera SE', '5°', '+2/0°', '12.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('27L', 'Ángulo pollera SE', '5°', '+2/0°', '12.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('28L', 'Ángulo pollera SE', '5°', '+2/0°', '12.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('29F', 'Distancia entre SE', '160 mm', '+/-0.5 mm', '12.0', '23/24');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('30F', 'Ángulo relativo zapatas', '80°', '+/-20''', '12.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('31F', 'Distancia entre SE', '160 mm', '+/-0.5 mm', '12.0', '28.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('32F', 'Ángulo relativo zapatas', '80°', '+/-20''', '12.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('33F', 'Distancia entre SE', '160 mm', '+/-0.5 mm', '12.0', '32/33');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('34F', 'Ángulo relativo zapatas', '80°', '+/-20''', '12.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('36F', 'Ángulo relativo zapatas', '60°', '+/-20''', '12.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('37F', 'Distancia entre SE', '160 mm', '+/-0.5 mm', '12.0', '20/21');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('38F', 'Ángulo relativo zapatas', '60°', '+/-20''', '12.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('39L', 'Ángulo pollera SE', '5°', '+/-1°', '11.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('40L', 'Ángulo pollera SE', '5°', '+2/0°', '11.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('41L', 'Ángulo pollera SE', '5°', '+2/0°', '11.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('42L', 'Ángulo pollera SE', '5°', '+2/0°', '11.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('43L', 'Ángulo pollera SE', '5°', '+2/0°', '11.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('44F', 'Distancia entre SE', '340 mm', '+/-0.5 mm', '11.0', '23/24');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('45F', 'Ángulo relativo zapatas', '80°', '+/-20''', '11.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('46F', 'Distancia entre SE', '340 mm', '+/-0.5 mm', '11.0', '28.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('47F', 'Ángulo relativo zapatas', '80°', '+/-20''', '11.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('48F', 'Distancia entre SE', '340 mm', '+/-0.5 mm', '11.0', '32/33');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('49F', 'Ángulo relativo zapatas', '80°', '+/-20''', '11.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('51F', 'Ángulo relativo zapatas', '60°', '+/-20''', '11.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('52F', 'Distancia entre SE', '340 mm', '+/-0.5 mm', '11.0', '20/21');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('53F', 'Ángulo relativo zapatas', '60°', '+/-20''', '11.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('54L', 'Ángulo pollera SE', '5°', '+/-1°', '10.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('55L', 'Ángulo pollera SE', '5°', '+2/0°', '10.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('56L', 'Ángulo pollera SE', '5°', '+2/0°', '10.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('57L', 'Ángulo pollera SE', '5°', '+2/0°', '10.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('58L', 'Ángulo pollera SE', '5°', '+2/0°', '10.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('59F', 'Distancia entre SE', '400 mm', '+/-0.5 mm', '10.0', '23/24');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('60F', 'Ángulo relativo zapatas', '80°', '+/-20''', '10.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('61F', 'Distancia entre SE', '400 mm', '+/-0.5 mm', '10.0', '28.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('62F', 'Ángulo relativo zapatas', '80°', '+/-20''', '10.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('63F', 'Distancia entre SE', '400 mm', '+/-0.5 mm', '10.0', '32/33');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('64F', 'Ángulo relativo zapatas', '80°', '+/-20''', '10.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('66F', 'Ángulo relativo zapatas', '60°', '+/-20''', '10.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('67F', 'Distancia entre SE', '400 mm', '+/-0.5 mm', '10.0', '20/21');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('68F', 'Ángulo relativo zapatas', '60°', '+/-20''', '10.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('69L', 'Ángulo pollera SE', '5°', '+/-1°', '9.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('70L', 'Ángulo pollera SE', '5°', '+2/0°', '9.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('71L', 'Ángulo pollera SE', '5°', '+2/0°', '9.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('72L', 'Ángulo pollera SE', '5°', '+2/0°', '9.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('73L', 'Ángulo pollera SE', '5°', '+2/0°', '9.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('74F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '9.0', '23/24');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('75F', 'Ángulo relativo zapatas', '80°', '+/-20''', '9.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('76F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '9.0', '28.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('77F', 'Ángulo relativo zapatas', '80°', '+/-20''', '9.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('78F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '9.0', '32/33');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('79F', 'Ángulo relativo zapatas', '80°', '+/-20''', '9.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('81F', 'Ángulo relativo zapatas', '60°', '+/-20''', '9.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('82F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '9.0', '20/21');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('83F', 'Ángulo relativo zapatas', '60°', '+/-20''', '9.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('84L', 'Ángulo pollera SE', '5°', '+/-1°', '8.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('85L', 'Ángulo pollera SE', '5°', '+2/0°', '8.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('86L', 'Ángulo pollera SE', '5°', '+2/0°', '8.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('87L', 'Ángulo pollera SE', '5°', '+2/0°', '8.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('88L', 'Ángulo pollera SE', '5°', '+2/0°', '8.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('89F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '8.0', '23/24');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('90F', 'Ángulo relativo zapatas', '80°', '+/-20''', '8.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('91F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '8.0', '28.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('92F', 'Ángulo relativo zapatas', '80°', '+/-20''', '8.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('93F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '8.0', '32/33');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('94F', 'Ángulo relativo zapatas', '80°', '+/-20''', '8.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('96F', 'Ángulo relativo zapatas', '60°', '+/-20''', '8.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('97F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '8.0', '20/21');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('98F', 'Ángulo relativo zapatas', '60°', '+/-20''', '8.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('99L', 'Ángulo pollera SE', '5°', '+/-1°', '7.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('100L', 'Ángulo pollera SE', '5°', '+2/0°', '7.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('101L', 'Ángulo pollera SE', '5°', '+2/0°', '7.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('102L', 'Ángulo pollera SE', '5°', '+2/0°', '7.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('103L', 'Ángulo pollera SE', '5°', '+2/0°', '7.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('104F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '7.0', '23/24');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('105F', 'Ángulo relativo zapatas', '80°', '+/-20''', '7.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('106F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '7.0', '28.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('107F', 'Ángulo relativo zapatas', '80°', '+/-20''', '7.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('108F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '7.0', '32/33');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('109F', 'Ángulo relativo zapatas', '80°', '+/-20''', '7.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('111F', 'Ángulo relativo zapatas', '60°', '+/-20''', '7.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('112F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '7.0', '20/21');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('113F', 'Ángulo relativo zapatas', '60°', '+/-20''', '7.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('114L', 'Ángulo pollera SE', '5°', '+/-1°', '6.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('115L', 'Ángulo pollera SE', '5°', '+2/0°', '6.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('116L', 'Ángulo pollera SE', '5°', '+2/0°', '6.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('117L', 'Ángulo pollera SE', '5°', '+2/0°', '6.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('118L', 'Ángulo pollera SE', '5°', '+2/0°', '6.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('119F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '6.0', '23/24');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('120F', 'Ángulo relativo zapatas', '80°', '+/-20''', '6.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('121F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '6.0', '28.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('122F', 'Ángulo relativo zapatas', '80°', '+/-20''', '6.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('123F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '6.0', '32/33');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('124F', 'Ángulo relativo zapatas', '80°', '+/-20''', '6.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('126F', 'Ángulo relativo zapatas', '60°', '+/-20''', '6.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('127F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '6.0', '20/21');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('128F', 'Ángulo relativo zapatas', '60°', '+/-20''', '6.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('129L', 'Ángulo pollera SE', '5°', '+/-1°', '5.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('130L', 'Ángulo pollera SE', '5°', '+2/0°', '5.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('131L', 'Ángulo pollera SE', '5°', '+2/0°', '5.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('132L', 'Ángulo pollera SE', '5°', '+2/0°', '5.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('133L', 'Ángulo pollera SE', '5°', '+2/0°', '5.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('134F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '5.0', '23/24');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('135F', 'Ángulo relativo zapatas', '80°', '+/-20''', '5.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('136F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '5.0', '28.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('137F', 'Ángulo relativo zapatas', '80°', '+/-20''', '5.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('138F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '5.0', '32/33');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('139F', 'Ángulo relativo zapatas', '80°', '+/-20''', '5.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('141F', 'Ángulo relativo zapatas', '60°', '+/-20''', '5.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('142F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '5.0', '20/21');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('143F', 'Ángulo relativo zapatas', '60°', '+/-20''', '5.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('144L', 'Ángulo pollera SE', '5°', '+/-1°', '4.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('145L', 'Ángulo pollera SE', '5°', '+2/0°', '4.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('146L', 'Ángulo pollera SE', '5°', '+2/0°', '4.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('147L', 'Ángulo pollera SE', '5°', '+2/0°', '4.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('148L', 'Ángulo pollera SE', '5°', '+2/0°', '4.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('149F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '4.0', '23/24');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('150F', 'Ángulo relativo zapatas', '80°', '+/-20''', '4.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('151F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '4.0', '28.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('152F', 'Ángulo relativo zapatas', '80°', '+/-20''', '4.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('153F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '4.0', '32/33');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('154F', 'Ángulo relativo zapatas', '80°', '+/-20''', '4.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('156F', 'Ángulo relativo zapatas', '60°', '+/-20''', '4.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('157F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '4.0', '20/21');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('158F', 'Ángulo relativo zapatas', '60°', '+/-20''', '4.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('159L', 'Ángulo pollera SE', '5°', '+/-1°', '3.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('160L', 'Ángulo pollera SE', '5°', '+2/0°', '3.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('161L', 'Ángulo pollera SE', '5°', '+2/0°', '3.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('162L', 'Ángulo pollera SE', '5°', '+2/0°', '3.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('163L', 'Ángulo pollera SE', '5°', '+2/0°', '3.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('164F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '3.0', '23/24');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('165F', 'Ángulo relativo zapatas', '80°', '+/-20''', '3.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('166F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '3.0', '28.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('167F', 'Ángulo relativo zapatas', '80°', '+/-20''', '3.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('168F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '3.0', '32/33');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('169F', 'Ángulo relativo zapatas', '80°', '+/-20''', '3.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('171F', 'Ángulo relativo zapatas', '60°', '+/-20''', '3.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('172F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '3.0', '20/21');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('173F', 'Ángulo relativo zapatas', '60°', '+/-20''', '3.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('174L', 'Ángulo pollera SE', '5°', '+/-1°', '2.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('175L', 'Ángulo pollera SE', '5°', '+2/0°', '2.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('176L', 'Ángulo pollera SE', '5°', '+2/0°', '2.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('177L', 'Ángulo pollera SE', '5°', '+2/0°', '2.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('178L', 'Ángulo pollera SE', '5°', '+2/0°', '2.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('179F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '2.0', '23/24');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('180F', 'Ángulo relativo zapatas', '80°', '+/-20''', '2.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('181F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '2.0', '28.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('182F', 'Ángulo relativo zapatas', '80°', '+/-20''', '2.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('183F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '2.0', '32/33');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('184F', 'Ángulo relativo zapatas', '80°', '+/-20''', '2.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('186F', 'Ángulo relativo zapatas', '60°', '+/-20''', '2.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('187F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '2.0', '20/21');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('188F', 'Ángulo relativo zapatas', '60°', '+/-20''', '2.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('189L', 'Ángulo pollera SE', '5°', '+/-1°', '1.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('190L', 'Ángulo pollera SE', '5°', '+2/0°', '1.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('191L', 'Ángulo pollera SE', '5°', '+2/0°', '1.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('192L', 'Ángulo pollera SE', '5°', '+2/0°', '1.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('193L', 'Ángulo pollera SE', '5°', '+2/0°', '1.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('194F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '1.0', '23/24');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('195F', 'Ángulo relativo zapatas', '80°', '+/-20''', '1.0', '26.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('196F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '1.0', '28.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('197F', 'Ángulo relativo zapatas', '80°', '+/-20''', '1.0', '30.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('198F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '1.0', '32/33');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('199F', 'Ángulo relativo zapatas', '80°', '+/-20''', '1.0', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('201F', 'Ángulo relativo zapatas', '60°', '+/-20''', '1.0', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('202F', 'Distancia entre SE', '455 mm', '+/-0.8 mm', '1.0', '20/21');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('203F', 'Ángulo relativo zapatas', '60°', '+/-20''', '1.0', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('001F', 'Ángulo pollera SE', '5°', '+/-1°', 'PP', '20-21');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('210F', 'Ángulo pollera SE', '5°', '+2/0°', 'PP', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('002F', 'Ángulo pollera SE', '5°', '+2/0°', 'PP', '32/33');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('211F', 'Ángulo pollera SE', '5°', '+2/0°', 'PP', '28.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('003F', 'Ángulo pollera SE', '5°', '+2/0°', 'PP', '23/24');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('212L', 'Ángulo de zapatas (3x1)', '5°', '+0/1°', 'PP', '23/24');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('213L', 'Ángulo de zapatas (3x1)', '5°', '+0/1°', 'PP', '29/30');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('214L', 'Ángulo de zapatas (3x1)', '5°', '+0/1°', 'PP', '35/36');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('216L', 'Presencia de soldadura TVS', 'NA', 'NA', 'Anillo', '23/24');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('217L', 'Presencia de soldadura TVS', 'NA', 'NA', 'Anillo', '35/36');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('218L', 'Presencia de soldadura TVS', 'NA', 'NA', 'Anillo', '29/30');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('222L', 'Deformación TS', 'NA', 'NA', 'PP', '23/24');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('223L', 'Deformación TS', 'NA', 'NA', 'PP', '20/21');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('224L', 'Deformación TS', 'NA', 'NA', 'PP', '35/36');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('225L', 'Deformación TS', 'NA', 'NA', 'PP', '32/33');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('226L', 'Deformación TS', 'NA', 'NA', 'PP', '29/30');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('227L', 'Deformación TS', 'NA', 'NA', 'PP', '26/27');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('228L', 'Deformación TVI', 'NA', 'NA', 'Anillo', '22.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('229L', 'Deformación TVI', 'NA', 'NA', 'Anillo', '37.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('230L', 'Deformación TVI', 'NA', 'NA', 'Anillo', '34.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('231L', 'Deformación TVI', 'NA', 'NA', 'Anillo', '31.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('232L', 'Deformación TVI', 'NA', 'NA', 'Anillo', '28.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('233L', 'Deformación TVI', 'NA', 'NA', 'Anillo', '25.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('240F', 'Identificación Acople', 'NA', 'NA', 'Acople', '28.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('241F', 'Identificación Acople', 'NA', 'NA', 'Acople', '28.0');
INSERT INTO control_names (control_id, control_name, valor_esperado, tolerancia, separador, barra) VALUES ('242F', 'Identificación Acople', 'NA', 'NA', 'Acople', '28.0');