#!/usr/bin/env python3
"""
Capture exact installed package versions from the conuar_env virtualenv
and write both requirements.txt and pyproject.toml (Poetry format).

Default paths (relative to this script's location):
  Venv    : ../../../conuar_env
  Output  : ../  (i.e. Conuar/conuar_webapp/)

Usage:
    # From the project root (Inspection_webapp/), activate venv first:
    python Conuar/conuar_webapp/deployment/freeze_env.py

    # Or point at any specific venv:
    python Conuar/conuar_webapp/deployment/freeze_env.py --venv /path/to/venv

    # Write outputs to a custom directory:
    python Conuar/conuar_webapp/deployment/freeze_env.py --out-dir ./deploy
"""

import argparse
import subprocess
import sys
import json
from pathlib import Path
from datetime import datetime

# ---------------------------------------------------------------------------
# Defaults — resolved relative to THIS file so the script works from anywhere
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent          # .../deployment/
DEFAULT_VENV = SCRIPT_DIR / ".." / ".." / ".." / "Conuar/conuar_env"   # Inspection_webapp/conuar_env
DEFAULT_OUT  = SCRIPT_DIR / ".."                      # .../conuar_webapp/

# Packages that pip installs automatically and are NOT managed by Poetry
_SKIP = {"pip", "setuptools", "wheel", "distribute", "pkg_resources"}


def _python_bin(venv_path: Path) -> str:
    """Return the python executable inside a venv (cross-platform)."""
    win = venv_path / "Scripts" / "python.exe"
    unix = venv_path / "bin" / "python"
    if win.exists():
        return str(win)
    if unix.exists():
        return str(unix)
    raise FileNotFoundError(
        f"No python executable found in {venv_path}. "
        "Make sure the path is a valid virtualenv."
    )


def get_packages(python_bin: str) -> list[dict]:
    """Return list of {name, version} dicts from pip list."""
    result = subprocess.run(
        [python_bin, "-m", "pip", "list", "--format=json"],
        capture_output=True, text=True, check=True
    )
    return json.loads(result.stdout)


def get_python_version(python_bin: str) -> str:
    """Return the major.minor version string of the given interpreter."""
    result = subprocess.run(
        [python_bin, "-c", "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')"],
        capture_output=True, text=True, check=True
    )
    return result.stdout.strip()


# ---------------------------------------------------------------------------
# requirements.txt
# ---------------------------------------------------------------------------

def write_requirements(packages: list[dict], output: Path) -> None:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        f"# Auto-generated by freeze_env.py on {timestamp}\n",
        "# Exact versions from conuar_env virtualenv\n",
        "\n",
    ]
    for pkg in sorted(packages, key=lambda p: p["name"].lower()):
        lines.append(f"{pkg['name']}=={pkg['version']}\n")
    output.write_text("".join(lines), encoding="utf-8")
    print(f"  [OK] requirements.txt  -> {output}")


# ---------------------------------------------------------------------------
# pyproject.toml (Poetry format)
# ---------------------------------------------------------------------------

def _poetry_deps_block(packages: list[dict], python_minor: str) -> str:
    lines = [
        "[tool.poetry.dependencies]",
        f'python = "^{python_minor}"',
    ]
    for pkg in sorted(packages, key=lambda p: p["name"].lower()):
        if pkg["name"].lower() in _SKIP:
            continue
        # Poetry uses the canonical package name; keep original casing from pip
        lines.append(f'{pkg["name"]} = "=={pkg["version"]}"')
    return "\n".join(lines)


def _build_minimal_pyproject(packages: list[dict], python_minor: str) -> str:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    deps = _poetry_deps_block(packages, python_minor)
    return f"""\
# Auto-generated by freeze_env.py on {timestamp}
# Exact versions from conuar_env virtualenv

[tool.poetry]
name = "conuar-webapp"
version = "0.1.0"
description = "Conuar nuclear fuel rod inspection webapp"
authors = ["Conuar <carlos.arodriguez@mercadolibre.com>"]
readme = "README.md"

{deps}

[tool.poetry.group.dev.dependencies]
# Add dev-only tools here (e.g. pytest, black, isort)

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
"""


def write_pyproject(packages: list[dict], python_minor: str, output: Path) -> None:
    if output.exists():
        content = output.read_text(encoding="utf-8")
        marker = "[tool.poetry.dependencies]"
        if marker in content:
            start = content.index(marker)
            # Find the next top-level section after the deps block
            next_section = content.find("\n[", start + len(marker))
            deps_block = content[start: next_section if next_section != -1 else len(content)]
            new_block = _poetry_deps_block(packages, python_minor)
            content = content.replace(deps_block, new_block)
            output.write_text(content, encoding="utf-8")
            print(f"  [OK] pyproject.toml    -> {output}  (dependencies section updated)")
        else:
            # Append the deps block to the existing file
            content += "\n" + _poetry_deps_block(packages, python_minor) + "\n"
            output.write_text(content, encoding="utf-8")
            print(f"  [OK] pyproject.toml    -> {output}  (dependencies section appended)")
    else:
        output.write_text(_build_minimal_pyproject(packages, python_minor), encoding="utf-8")
        print(f"  [OK] pyproject.toml    -> {output}  (new file created)")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Freeze exact venv package versions to requirements.txt + pyproject.toml"
    )
    parser.add_argument(
        "--venv",
        default=str(DEFAULT_VENV),
        help=f"Path to the virtualenv directory (default: {DEFAULT_VENV})"
    )
    parser.add_argument(
        "--out-dir",
        default=str(DEFAULT_OUT),
        help=f"Directory where output files are written (default: {DEFAULT_OUT})"
    )
    args = parser.parse_args()

    venv_path = Path(args.venv).resolve()
    out_dir   = Path(args.out_dir).resolve()

    print(f"\nVirtualenv : {venv_path}")
    if not venv_path.exists():
        print(f"  ERROR: venv path does not exist: {venv_path}")
        sys.exit(1)

    python_bin = _python_bin(venv_path)
    print(f"Python bin : {python_bin}")

    packages = get_packages(python_bin)
    python_minor = get_python_version(python_bin)
    print(f"Python ver : {python_minor}")
    print(f"Packages   : {len(packages)} found")
    print(f"Output dir : {out_dir}\n")

    out_dir.mkdir(parents=True, exist_ok=True)

    write_requirements(packages, out_dir / "requirements.txt")
    write_pyproject(packages, python_minor, out_dir / "pyproject.toml")

    print(f"\nDone. Both files written to: {out_dir}")


if __name__ == "__main__":
    main()
