# Generated by Django 4.2.23 on 2025-08-31 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionphoto',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Inspection Photo', 'verbose_name_plural': 'Inspection Photos'},
        ),
        migrations.RenameField(
            model_name='inspectionphoto',
            old_name='taken_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='fuel_rod_type',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='inspection_id',
        ),
        migrations.AddField(
            model_name='inspection',
            name='completed_date',
            field=models.DateTimeField(blank=True, help_text='Date when inspection was completed', null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the inspection', null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_type',
            field=models.CharField(choices=[('quality', 'Quality Control'), ('safety', 'Safety Inspection'), ('compliance', 'Compliance Check'), ('performance', 'Performance Test'), ('visual', 'Visual Inspection')], default='quality', help_text='Type of inspection being performed', max_length=20),
        ),
        migrations.AddField(
            model_name='inspection',
            name='location',
            field=models.CharField(blank=True, help_text='Location where inspection was performed', max_length=200),
        ),
        migrations.AddField(
            model_name='inspection',
            name='product_code',
            field=models.CharField(blank=True, help_text='Product code or SKU', max_length=100),
        ),
        migrations.AddField(
            model_name='inspection',
            name='product_name',
            field=models.CharField(blank=True, help_text='Name of the product being inspected', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='recommendations',
            field=models.TextField(blank=True, help_text='Recommendations based on inspection'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='result',
            field=models.TextField(blank=True, help_text='Inspection results and findings'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='title',
            field=models.CharField(blank=True, help_text='Inspection title or name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Batch or lot number', max_length=100),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of inspection'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(help_text='User who performed the inspection', on_delete=django.db.models.deletion.CASCADE, related_name='inspections_conducted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial number if applicable', max_length=100),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the inspection', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor who reviewed the inspection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_supervised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspectionphoto',
            name='photo',
            field=models.ImageField(upload_to='inspections/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='inspectionphoto',
            name='photo_type',
            field=models.CharField(blank=True, help_text="Type of photo (e.g., 'before', 'after', 'defect', 'overview')", max_length=50),
        ),
    ]
