# Generated by Django 4.2.23 on 2025-09-06 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_inspectionphoto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(default='MAQ-001', max_length=50, unique=True)),
                ('name', models.CharField(default='Analizador de Combustible ArByte-3000', max_length=100)),
                ('model', models.CharField(default='AB-3000', max_length=50)),
                ('version', models.CharField(default='v2.1.3', max_length=20)),
                ('status', models.CharField(choices=[('offline', 'Desconectada'), ('idle', 'En Espera'), ('calibrating', 'Calibrando'), ('inspecting', 'Inspeccionando'), ('maintenance', 'En Mantenimiento'), ('error', 'Error')], default='offline', help_text='Estado actual de la máquina', max_length=20)),
                ('current_stage', models.CharField(blank=True, choices=[('initialization', 'Inicialización'), ('sample_preparation', 'Preparación de Muestra'), ('analysis', 'Análisis en Progreso'), ('quality_check', 'Verificación de Calidad'), ('report_generation', 'Generación de Reporte'), ('completion', 'Finalización')], help_text='Etapa actual del proceso de inspección', max_length=30, null=True)),
                ('total_inspections', models.PositiveIntegerField(default=0, help_text='Total de inspecciones realizadas')),
                ('inspections_today', models.PositiveIntegerField(default=0, help_text='Inspecciones realizadas hoy')),
                ('uptime_hours', models.FloatField(default=0.0, help_text='Horas de funcionamiento')),
                ('last_inspection', models.DateTimeField(blank=True, help_text='Última inspección realizada', null=True)),
                ('last_maintenance', models.DateTimeField(blank=True, help_text='Último mantenimiento', null=True)),
                ('success_rate', models.FloatField(default=100.0, help_text='Tasa de éxito de inspecciones (%)')),
                ('average_inspection_time', models.FloatField(default=0.0, help_text='Tiempo promedio de inspección (minutos)')),
                ('last_status_change', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Máquina de Inspección',
                'verbose_name_plural': 'Máquinas de Inspección',
            },
        ),
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['-inspection_date'], 'verbose_name': 'Inspección', 'verbose_name_plural': 'Inspecciones'},
        ),
        migrations.AlterModelOptions(
            name='inspectionphoto',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Foto de Inspección', 'verbose_name_plural': 'Fotos de Inspección'},
        ),
        migrations.AlterField(
            model_name='inspection',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Número de lote o partida', max_length=100),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='completed_date',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se completó la inspección', null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción detallada de la inspección', null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la inspección'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_type',
            field=models.CharField(choices=[('quality', 'Control de Calidad'), ('safety', 'Inspección de Seguridad'), ('compliance', 'Verificación de Cumplimiento'), ('performance', 'Prueba de Rendimiento'), ('visual', 'Inspección Visual')], default='quality', help_text='Tipo de inspección que se está realizando', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(help_text='Usuario que realizó la inspección', on_delete=django.db.models.deletion.CASCADE, related_name='inspections_conducted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='location',
            field=models.CharField(blank=True, help_text='Ubicación donde se realizó la inspección', max_length=200),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas adicionales o comentarios'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='product_code',
            field=models.CharField(blank=True, help_text='Código del producto o SKU', max_length=100),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='product_name',
            field=models.CharField(blank=True, help_text='Nombre del producto que se está inspeccionando', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='recommendations',
            field=models.TextField(blank=True, help_text='Recomendaciones basadas en la inspección'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='result',
            field=models.TextField(blank=True, help_text='Resultados y hallazgos de la inspección'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Número de serie si aplica', max_length=100),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('failed', 'Fallida'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', help_text='Estado actual de la inspección', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor que revisó la inspección', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_supervised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='title',
            field=models.CharField(blank=True, help_text='Título o nombre de la inspección', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionphoto',
            name='photo_type',
            field=models.CharField(blank=True, help_text="Tipo de foto (ej., 'antes', 'después', 'defecto', 'vista general')", max_length=50),
        ),
        migrations.CreateModel(
            name='MachineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('status_change', 'Cambio de Estado'), ('inspection_start', 'Inicio de Inspección'), ('inspection_complete', 'Inspección Completada'), ('maintenance', 'Mantenimiento'), ('error', 'Error'), ('calibration', 'Calibración')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main.inspectionmachine')),
            ],
            options={
                'verbose_name': 'Registro de Máquina',
                'verbose_name_plural': 'Registros de Máquina',
                'ordering': ['-timestamp'],
            },
        ),
    ]
