# Generated by Django 4.2.24 on 2025-09-07 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_inspectionmachine_alter_inspection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_storage_path', models.CharField(default='media/inspection_photos/', help_text='Ruta de almacenamiento para archivos multimedia', max_length=500)),
                ('camera_1_ip', models.GenericIPAddressField(default='192.168.1.100', help_text='Dirección IP de la Cámara 1')),
                ('camera_2_ip', models.GenericIPAddressField(default='192.168.1.101', help_text='Dirección IP de la Cámara 2')),
                ('camera_3_ip', models.GenericIPAddressField(default='192.168.1.102', help_text='Dirección IP de la Cámara 3')),
                ('plc_ip', models.GenericIPAddressField(default='192.168.1.50', help_text='Dirección IP del PLC que controla la máquina de inspección')),
                ('plc_port', models.PositiveIntegerField(default=502, help_text='Puerto del PLC (por defecto 502 para Modbus)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuario que realizó la última actualización', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
