# Generated by Django 4.2.24 on 2025-09-07 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_systemconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionmachine',
            name='current_inspection',
            field=models.OneToOneField(blank=True, help_text='Inspección actual de la máquina', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine', to='main.inspection'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='description',
            field=models.TextField(default='Inspección de calidad de combustible utilizando el sistema ArByte-3000', help_text='Descripción detallada de la inspección'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('failed', 'Fallida'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='completed', help_text='Estado actual de la inspección', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='title',
            field=models.CharField(default='Inspección de Combustible ArByte', help_text='Título o nombre de la inspección', max_length=200),
        ),
    ]
