# Generated by Django 4.2.23 on 2025-09-14 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_inspectionmachine_current_inspection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='defecto_encontrado',
            field=models.BooleanField(default=False, help_text='Indica si se encontró un defecto durante la inspección (detectado por cámara)'),
        ),
        migrations.AddField(
            model_name='inspectionmachine',
            name='total_defects_found',
            field=models.PositiveIntegerField(default=0, help_text='Total de defectos encontrados en todas las inspecciones'),
        ),
        migrations.AddField(
            model_name='inspectionphoto',
            name='defecto_encontrado',
            field=models.BooleanField(default=False, help_text='Indica si esta foto específica muestra un defecto detectado por la cámara'),
        ),
        migrations.CreateModel(
            name='InspectionPlcEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_plc', models.DateTimeField(help_text='Timestamp del PLC')),
                ('execution_id', models.CharField(help_text='ID ejecución: Entre descanso y descanso', max_length=100)),
                ('control_point_id', models.CharField(help_text='ID punto de control: Ej. Zapata num. 5', max_length=100)),
                ('execution_type', models.CharField(choices=[('automatic', 'Automático'), ('manual', 'Manual'), ('free', 'Libre')], help_text='Tipo de ejecución', max_length=20)),
                ('control_point_label', models.CharField(blank=True, help_text='Etiqueta punto de control (solo para rutinas no libres)', max_length=200)),
                ('x_control_point', models.FloatField(help_text='X punto de control')),
                ('y_control_point', models.FloatField(help_text='Y punto de control')),
                ('z_control_point', models.FloatField(help_text='Z punto de control')),
                ('plate_angle', models.FloatField(help_text='Ángulo del plato')),
                ('control_point_creator', models.CharField(help_text='Usuario creador punto de control', max_length=100)),
                ('program_creator', models.CharField(help_text='Usuario creador Programa', max_length=100)),
                ('program_version', models.CharField(help_text='Version del programa', max_length=50)),
                ('camera_id', models.CharField(help_text='ID Cámara', max_length=50)),
                ('filming_type', models.CharField(choices=[('video', 'Video'), ('photo', 'Foto')], help_text='Tipo filmación', max_length=20)),
                ('last_photo_request_timestamp', models.DateTimeField(blank=True, help_text='Último timestamp solicitud foto cámara', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_inspection', models.ForeignKey(help_text='ID de la inspección relacionada', on_delete=django.db.models.deletion.CASCADE, related_name='plc_events', to='main.inspection')),
            ],
            options={
                'verbose_name': 'Evento PLC de Inspección',
                'verbose_name_plural': 'Eventos PLC de Inspección',
                'ordering': ['-timestamp_plc'],
            },
        ),
    ]
