# Generated by Django 4.2.23 on 2025-09-14 16:41

from django.db import migrations


def update_photo_paths(apps, schema_editor):
    """Update existing photo paths to include Inspection_1 folder"""
    InspectionPhoto = apps.get_model('main', 'InspectionPhoto')
    
    # Update all existing photos to use the new path structure
    for photo in InspectionPhoto.objects.all():
        if photo.photo and 'inspection_photos/' in photo.photo.name:
            # Extract the filename from the current path
            filename = photo.photo.name.split('/')[-1]
            # Update to new path structure
            new_path = f'inspection_photos/Inspection_{photo.inspection.id}/{filename}'
            photo.photo.name = new_path
            photo.save()


def reverse_photo_paths(apps, schema_editor):
    """Reverse the photo path update"""
    InspectionPhoto = apps.get_model('main', 'InspectionPhoto')
    
    # Revert all photos to the old path structure
    for photo in InspectionPhoto.objects.all():
        if photo.photo and 'Inspection_' in photo.photo.name:
            # Extract the filename from the current path
            filename = photo.photo.name.split('/')[-1]
            # Revert to old path structure
            old_path = f'inspection_photos/{filename}'
            photo.photo.name = old_path
            photo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_inspection_defecto_encontrado_and_more'),
    ]

    operations = [
        migrations.RunPython(update_photo_paths, reverse_photo_paths),
    ]
