# Generated by Django 4.2.23 on 2025-09-14 17:25

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_update_photo_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionphoto',
            name='photo',
            field=models.ImageField(upload_to=main.models.inspection_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='media_storage_path',
            field=models.CharField(default='media/inspection_photos/Inspection_1/', help_text='Ruta de almacenamiento para archivos multimedia', max_length=500),
        ),
        migrations.CreateModel(
            name='PlcReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_plc', models.DateTimeField(help_text='Timestamp del PLC')),
                ('id_inspection', models.IntegerField(help_text='ID de la inspección')),
                ('execution_id', models.IntegerField(help_text='ID ejecución')),
                ('control_point_id', models.IntegerField(help_text='ID punto de control')),
                ('execution_type', models.IntegerField(help_text='Tipo de ejecución (1=automatic, 2=manual, 3=free)')),
                ('control_point_label', models.IntegerField(help_text='Etiqueta punto de control')),
                ('x_control_point', models.FloatField(help_text='X punto de control')),
                ('y_control_point', models.FloatField(help_text='Y punto de control')),
                ('z_control_point', models.FloatField(help_text='Z punto de control')),
                ('plate_angle', models.FloatField(help_text='Ángulo del plato')),
                ('control_point_creator', models.IntegerField(help_text='Usuario creador punto de control')),
                ('program_creator', models.IntegerField(help_text='Usuario creador Programa')),
                ('program_version', models.IntegerField(help_text='Version del programa')),
                ('camera_id', models.IntegerField(help_text='ID Cámara')),
                ('filming_type', models.IntegerField(help_text='Tipo filmación (1=video, 2=photo)')),
                ('last_photo_request_timestamp', models.IntegerField(help_text='Último timestamp solicitud foto cámara')),
                ('new_photos_available', models.BooleanField(default=False, help_text='Flag indicando nuevas fotos')),
                ('photo_count', models.IntegerField(default=0, help_text='Número de nuevas fotos')),
                ('processed', models.BooleanField(default=False, help_text='Indica si el registro ya fue procesado')),
                ('processing_error', models.TextField(blank=True, help_text='Error durante el procesamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lectura PLC',
                'verbose_name_plural': 'Lecturas PLC',
                'ordering': ['-timestamp_plc'],
                'indexes': [models.Index(fields=['processed', 'timestamp_plc'], name='main_plcrea_process_3f539c_idx'), models.Index(fields=['id_inspection'], name='main_plcrea_id_insp_1a8452_idx')],
            },
        ),
    ]
