# Generated by Django 4.2.23 on 2025-09-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_inspection_type_to_tipo_combustible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_inspector',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_supervisor',
        ),
        migrations.AddField(
            model_name='plcreading',
            name='tipo_combustible',
            field=models.IntegerField(default=1, help_text='Tipo de combustible (1=uranio, 2=plutonio, 3=otros)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspection',
            name='tipo_combustible',
            field=models.CharField(choices=[('uranio', 'Uranio'), ('plutonio', 'Plutonio')], default='uranio', help_text='Tipo de combustible que se está inspeccionando', max_length=20),
        ),
    ]
