# Generated by Django 4.2.23 on 2025-09-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_user_is_inspector_remove_user_is_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_enabled',
            field=models.BooleanField(default=False, help_text='Allow user to reset their password (only superuser can enable this)'),
        ),
    ]
