# Generated by Django 4.2.23 on 2025-09-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_add_password_reset_enabled_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, help_text='Secure token for password reset (generated by superuser)', max_length=100, null=True),
        ),
    ]
