# Generated by Django 4.2.23 on 2025-09-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_add_password_reset_token_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_expired',
            field=models.BooleanField(default=False, help_text='Indicates if password has expired and must be changed'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_expiry_date',
            field=models.DateTimeField(blank=True, help_text='Date when password expires (90 days from last change)', null=True),
        ),
    ]
