# Generated by Django 4.2.23 on 2025-09-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_add_password_expiry_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionplcevent',
            name='fuel_rig_id',
            field=models.CharField(blank=True, help_text='ID del rig de combustible nuclear siendo inspeccionado', max_length=50),
        ),
        migrations.AddField(
            model_name='inspectionplcevent',
            name='message_body',
            field=models.TextField(blank=True, help_text="Cuerpo del mensaje del sistema (ej. 'machine active', 'machine emergency stop')"),
        ),
        migrations.AddField(
            model_name='inspectionplcevent',
            name='message_type',
            field=models.CharField(choices=[('machine_routine_step', 'Paso de Rutina de Máquina'), ('system_message', 'Mensaje del Sistema')], default='machine_routine_step', help_text='Tipo de mensaje: rutina de máquina o mensaje del sistema', max_length=30),
        ),
        migrations.AddField(
            model_name='plcreading',
            name='fuel_rig_id',
            field=models.CharField(blank=True, help_text='ID del rig de combustible nuclear siendo inspeccionado', max_length=50),
        ),
        migrations.AddField(
            model_name='plcreading',
            name='message_body',
            field=models.TextField(blank=True, help_text="Cuerpo del mensaje del sistema (ej. 'machine active', 'machine emergency stop')"),
        ),
        migrations.AddField(
            model_name='plcreading',
            name='message_type',
            field=models.CharField(choices=[('machine_routine_step', 'Paso de Rutina de Máquina'), ('system_message', 'Mensaje del Sistema')], default='machine_routine_step', help_text='Tipo de mensaje: rutina de máquina o mensaje del sistema', max_length=30),
        ),
    ]
