# Generated by Django 4.2.23 on 2025-11-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_plcdataraw'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='plcdataraw',
            new_name='plc_data_ra_timesta_978630_idx',
            old_name='plc_data_ra_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='plcdataraw',
            new_name='plc_data_ra_process_371d64_idx',
            old_name='plc_data_ra_process_idx',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='supervisor',
        ),
    ]
